// Auto-generated at build time by scripts/generate-content.mjs
// Do not edit this file directly. Edit the Markdown files in content/ directory instead.
import type { ProjectData, BlogPostData, MateriData } from "./content"

export const projectsData: ProjectData[] = [
  {
    "slug": "cloud-orchestration",
    "title": "Cloud Infrastructure & Container Orchestration",
    "deskripsi": "Platform orkestrasi container otomatis berbasis Docker Swarm, Nginx reverse proxy dengan dynamic upstream, dan monitoring terpusat untuk aplikasi multi-tenant.",
    "tags": [
      "Docker Swarm",
      "Nginx",
      "Linux Automation",
      "Prometheus",
      "CI/CD"
    ],
    "category": "DevOps & Cloud",
    "featured": true,
    "date": "2024",
    "role": "DevOps & Systems Architect",
    "liveUrl": "",
    "githubUrl": "",
    "metrics": [
      {
        "label": "Cluster Uptime",
        "value": "99.98%"
      },
      {
        "label": "Deploy Time",
        "value": "< 45s"
      },
      {
        "label": "Zero-Downtime",
        "value": "Rolling Update"
      }
    ],
    "content": "\n# Cloud Infrastructure & Container Orchestration\n\nArsitektur infrastruktur server mandiri (bare-metal to VPS) yang dikonfigurasi untuk menjalankan klaster aplikasi web bervolume tinggi dengan efisiensi biaya maksimal.\n\n### Arsitektur Utama\n- **Docker Swarm Cluster**: Manajemen 4 node (1 Manager, 3 Workers) dengan automatic health check dan restart policy.\n- **Nginx Reverse Proxy**: Dynamic reverse proxying dengan Let's Encrypt automated renewal dan rate limiting untuk mitigasi DDoS.\n- **CI/CD Pipeline**: GitHub Actions terintegrasi untuk linting, automated testing, container image build, dan push ke private registry.\n- **Log Aggregation & Monitoring**: Stack monitoring terpusat untuk mendeteksi lonjakan memori, CPU throttle, dan error spike secara real-time.\n\n### Keunggulan\n- Rollout versi baru aplikasi tanpa downtime sedetik pun (rolling update).\n- Penghematan biaya infrastruktur cloud hingga 50% dibanding managed cloud kubernetes konvensional untuk kebutuhan skala menengah.\n"
  },
  {
    "slug": "erp-inventory",
    "title": "Enterprise ERP & Smart Inventory",
    "deskripsi": "Sistem Enterprise Resource Planning (ERP) terintegrasi untuk supply chain, manajemen pergudangan multi-cabang, barcode scanning, dan laporan keuangan real-time.",
    "tags": [
      "Laravel 11",
      "PostgreSQL",
      "Next.js",
      "Redis",
      "Tailwind CSS"
    ],
    "category": "Full-Stack",
    "featured": true,
    "date": "2024",
    "role": "Full-Stack Engineer",
    "liveUrl": "",
    "githubUrl": "",
    "metrics": [
      {
        "label": "Daily Transactions",
        "value": "15,000+"
      },
      {
        "label": "Query Speedup",
        "value": "68%"
      },
      {
        "label": "Branches",
        "value": "12 Hubs"
      }
    ],
    "content": "\n# Enterprise ERP & Smart Inventory\n\nSistem ERP berskala enterprise yang dirancang khusus untuk memodernisasi rantai pasok dan pergudangan ritel multi-cabang. Menggabungkan backend tangguh berbasis Laravel 11 dengan antarmuka front-end responsif dan performan.\n\n### Latar Belakang & Masalah\nManajemen inventaris konvensional di 12 cabang retail mengalami desinkronisasi stok hingga 14%, menyebabkan keterlambatan restock dan kesulitan dalam kalkulasi HPP (Harga Pokok Penjualan) secara akurat.\n\n### Solusi Arsitektur\n1. **Event-Driven Stock Sync**: Menggunakan event & listener Laravel dipadukan dengan Redis Queue untuk sinkronisasi inventaris multi-cabang tanpa memblokir request pengguna.\n2. **Database Sharding & Partitioning**: PostgreSQL dengan partisi tabel per kuartal fiskal untuk menjaga kecepatan agregasi laporan keuangan.\n3. **PWA Mobile Barcode**: Antarmuka scanning cepat berbasis Next.js untuk operator gudang lapangan dengan dukungan offline cache.\n\n### Dampak & Hasil\n- Desinkronisasi data berkurang hingga 0.02%.\n- Waktu pelaporan laba rugi bulanan berkurang dari 3 hari menjadi hitungan menit.\n- Skalabilitas siap mendukung ekspansi hingga 50 cabang.\n"
  },
  {
    "slug": "laravel-education",
    "title": "Sistem Informasi Pendidikan Terpadu",
    "deskripsi": "Platform administrasi komprehensif institusi pendidikan — mencakup portal akademik siswa, data master pendidik, absensi cerdas, dan e-raport kurikulum merdeka.",
    "tags": [
      "Laravel 10",
      "MySQL",
      "Livewire",
      "Tailwind CSS",
      "PDF Generation"
    ],
    "category": "Full-Stack",
    "featured": true,
    "date": "2023 - 2024",
    "role": "Lead Full-Stack Developer",
    "liveUrl": "",
    "githubUrl": "",
    "metrics": [
      {
        "label": "Siswa Terdaftar",
        "value": "2,400+"
      },
      {
        "label": "Cetak Raport",
        "value": "Instant (PDF)"
      },
      {
        "label": "Guru Aktif",
        "value": "140+"
      }
    ],
    "content": "\n# Sistem Informasi Pendidikan Terpadu\n\nPlatform administrasi institusi pendidikan yang dibangun khusus untuk menyederhanakan birokrasi sekolah, manajemen siswa, penjadwalan pelajaran, dan pelaporan nilai kurikulum merdeka.\n\n### Tantangan\nSistem terdahulu masih menggunakan spreadsheet terpisah yang rentan corrupt, penginputan nilai ganda oleh dewan guru, dan keterlambatan pencetakan raport hingga berhari-hari menjelang akhir semester.\n\n### Solusi Teknis\n- **Modular Multi-Role Authorization**: Pemisahan hak akses ketat antara Administrator, Guru Piket, Wali Kelas, Kepala Sekolah, dan Siswa/Wali Murid.\n- **Bulk Grade Processing**: Menggunakan chunked processing untuk kalkulasi ribuan nilai akhir siswa dan cetak raport PDF batch tanpa timeout.\n- **Audit Trails & Log Activity**: Seluruh perubahan nilai dan data sensitif tercatat secara rapi untuk akuntabilitas institusi."
  },
  {
    "slug": "sdm-module",
    "title": "Modul SDM & Payroll Otomatis",
    "deskripsi": "Sistem manajemen sumber daya manusia terintegrasi: data kepegawaian dinamis, kalkulasi potongan PPh 21 otomatis, cuti online, dan slip gaji terenkripsi.",
    "tags": [
      "Laravel 11",
      "PostgreSQL",
      "Queue Worker",
      "REST API",
      "Docker"
    ],
    "category": "Backend & ERP",
    "featured": true,
    "date": "2024",
    "role": "Backend Architect",
    "liveUrl": "",
    "githubUrl": "",
    "metrics": [
      {
        "label": "Karyawan Dikelola",
        "value": "500+"
      },
      {
        "label": "Kalkulasi Payroll",
        "value": "< 10 Detik"
      },
      {
        "label": "Tingkat Akurasi",
        "value": "100%"
      }
    ],
    "content": "\n# Modul SDM & Payroll Otomatis\n\nModul manajemen sumber daya manusia (HRIS) terintegrasi yang dirancang sebagai micro-service modular untuk ekosistem ERP yang lebih luas.\n\n### Fitur Kunci\n- **Formula Payroll Dinamis**: Mengakomodasi tunjangan variabel, lembur, absensi berbasis geolocation & selfie, serta pemotongan pajak PPh 21 TER (Tarif Efektif Rata-Rata) terbaru.\n- **Workflow Persetujuan Cuti Berjenjang**: Pengajuan cuti terhubung dengan notifikasi email/webhook ke supervisor dan update sisa cuti otomatis.\n- **Security & Enkripsi Data Pribadi**: Enkripsi nomor rekening, data gaji pokok, dan generate slip PDF yang diproteksi password unik."
  }
]

export const postsData: BlogPostData[] = [
  {
    "slug": "hello-nextjs",
    "title": "Hello Next.js 16",
    "deskripsi": "",
    "tags": [
      "Next.js",
      "React",
      "Web Development"
    ],
    "date": "2024-07-21",
    "readingTime": "1 min read",
    "content": "\n# Pengantar Next.js 16\n\nNext.js 16 membawa banyak perbaikan dan fitur baru yang membuat pengembangan web menjadi lebih mudah dan performant.\n\n## Fitur Utama\n\n- **App Router** yang lebih stabil dan lengkap\n- **Server Components** untuk rendering di server\n- **Streaming** dan **Suspense** untuk UX yang lebih baik\n- **Img Component** yang dioptimalkan\n- **Middleware** yang lebih powerful\n\n## Memulai\n\n```bash\nnpx create-next-app@latest\n```\n\nAtau dalam proyek ini:\n\n```bash\npnpm dev\n```\n\n## Tips & Trik\n\n1. Gunakan `next/image` untuk images yang otomatis dioptimalkan\n2. Manfaatkan `loading=` untuk lazy loading\n3. Susun struktur folder dengan `page.tsx` untuk routing\n\n---\n\n*Diposting pada tanggal 21 Juli 2024 · 3 menit baca*"
  },
  {
    "slug": "prisma-to-static",
    "title": "Dari Prisma ke Static Markdown",
    "deskripsi": "",
    "tags": [
      "Prisma",
      "Static",
      "Markdown",
      "Next.js"
    ],
    "date": "2024-07-21",
    "readingTime": "1 min read",
    "content": "\n# Dari Prisma ke Static Markdown\n\nProyek ini sebelumnya menggunakan Prisma ORM dengan database PostgreSQL. Namun, untuk menghindari batasan free tier dan kompleksitas konfigurasi, kita memindahkan konten ke file markdown statis.\n\n## Alasan Perubahan\n\n- **Biaya**: Menghilangkan dependensi database (Neon, PlanetScale)\n- **Sederhana**: Konten disimpan sebagai file `.md` di folder saja\n- **Performansi**: No database query, hanya file system read\n- **Deploy**: Mudah deploy ke Cloudflare Workers tanpa database\n\n## Cara Kerja\n\n1. Tulis konten di file `.md` di folder `content/`\n2. Gunakan `fs` di runtime Next.js untuk membaca file\n3. Render markdown dengan `react-markdown` dan `rehype-highlight`\n4. Generate static page pada build time atau render di runtime\n\n## Manfaat\n\n- Biaya hosting murah (atau gratis)\n- Tidak perlu mengelola database schema\n- Konten bisa di-version dengan Git\n- Mudah migrasi antara platform\n\n---\n\n*Diposting pada tanggal 20 Juli 2024 · 4 menit baca*"
  }
]

export const materiData: MateriData[] = [
  {
    "slug": "laravel-intro",
    "title": "Pengantar Framework Laravel",
    "kelas": "Laravel Dasar",
    "deskripsi": "Mengenal arsitektur framework PHP Laravel 11, routing, blade engine, dan Eloquent ORM untuk pemula hingga menengah.",
    "tags": [
      "Laravel Dasar"
    ],
    "date": "2024-06-15",
    "readingTime": "2 min read",
    "content": "\n# Pengantar Framework Laravel\n\nLaravel adalah framework PHP modern yang paling populer di dunia karena sintaksnya yang ekspresif, elegan, dan ekosistemnya yang sangat matang untuk membangun aplikasi web berskala kecil hingga enterprise.\n\n## Mengapa Memilih Laravel?\n\n- **Sintaks yang Elegan & Readable**: Kode terasa intuitif dan mudah dipelajari oleh anggota tim baru.\n- **Ekosistem Sangat Lengkap**: Dukungan resmi untuk queue worker (Horizon), admin panel (Filament), full-stack reactivity (Livewire), dan deployment tooling (Forge).\n- **Database Migrations & Seeding**: Version control database yang aman, konsisten, dan mudah direplikasi antar developer.\n- **Eloquent ORM**: Abstraksi database tingkat tinggi yang mempermudah relasi data yang kompleks (One to Many, Many to Many, Polymorphic).\n- **Robust Queue System**: Pemrosesan background jobs seperti pengiriman email dan kalkulasi data berat di background worker.\n\n## Langkah Instalasi Dasar\n\nPastikan Composer dan PHP 8.2+ sudah terpasang di sistem operasi Anda:\n\n```bash\ncomposer create-project laravel/laravel portofolio-app\ncd portofolio-app\n```\n\nJalankan local development server:\n\n```bash\nphp artisan serve\n```\n\n## Konfigurasi Penting\n\n1. Sesuaikan variabel database pada file `.env`:\n```env\nDB_CONNECTION=mysql\nDB_HOST=127.0.0.1\nDB_PORT=3306\nDB_DATABASE=app_db\nDB_USERNAME=root\nDB_PASSWORD=\n```\n2. Generate Application Encryption Key:\n```bash\nphp artisan key:generate\n```\n3. Eksekusi migrasi tabel:\n```bash\nphp artisan migrate\n```\n\nSelamat belajar! Arsitektur Laravel siap mengawal project sistem informasi Anda menjadi scalable dan reliable."
  },
  {
    "slug": "nextjs-basics",
    "title": "Dasar-dasar Next.js 16 (App Router)",
    "kelas": "Next.js Dasar",
    "deskripsi": "Pahami fundamental Next.js App Router, Server Components, Streaming, dan optimasi static rendering tanpa database.",
    "tags": [
      "Next.js Dasar"
    ],
    "date": "2024-05-10",
    "readingTime": "2 min read",
    "content": "\n# Dasar-dasar Next.js 16 (App Router)\n\nNext.js adalah React Framework untuk produksi yang mengombinasikan kecepatan Static Site Generation (SSG) dengan kapabilitas Server Components modern.\n\n## 4 Pilar Utama Next.js App Router\n\n### 1. React Server Components (RSC) Secara Default\nSemua komponen di dalam direktori `app/` secara default dieksekusi di server. Manfaatnya:\n- Ukuran bundle JavaScript di browser menjadi jauh lebih ringan (0-bundle size untuk dependencies server).\n- Keamanan lebih terjamin karena credential dan API secret tidak pernah bocor ke client.\n\n### 2. Client Components (`\"use client\"`)\nKetika komponen memerlukan interaktivitas, state (`useState`), effect (`useEffect`), atau event handler browser (`onClick`, `framer-motion`), cukup tambahkan direktif `\"use client\"` di baris paling atas file.\n\n```tsx\n\"use client\"\n\nimport { useState } from 'react'\n\nexport default function Counter() {\n  const [count, setCount] = useState(0)\n  return (\n    <button onClick={() => setCount(c => c + 1)}>\n      Clicked: {count}\n    </button>\n  )\n}\n```\n\n### 3. File-System Based Routing\n- `page.tsx`: File tampilan halaman publik.\n- `layout.tsx`: Kerangka bersama (header, footer, nav) yang mempertahankan state antar navigasi.\n- `loading.tsx`: UI fallback berbasis React Suspense otomatis.\n- `error.tsx`: Error boundary untuk menangani crash pada segmen route.\n\n### 4. Zero-Database Static Architecture\nAnda bisa membangun website portofolio, blog, maupun dokumentasi super cepat hanya dengan file Markdown lokal via `fs` dan `gray-matter`. Tanpa database server, tanpa biaya bulanan, dan waktu load mendekati instan!"
  }
]

export const aboutContent: string = "\n# Muhammad Habib Abdillah\n\nSaya adalah seorang **Full-Stack Developer** dengan pengalaman lebih dari 3 tahun berfokus pada arsitektur sistem informasi modular, backend skala tinggi, dan pengembangan antarmuka modern yang responsif dan elegan.\n\nBerpengalaman merancang ekosistem aplikasi enterprise menggunakan **PHP (Laravel)**, **Node.js**, **Next.js**, **PostgreSQL/MySQL**, dan containerisasi **Docker**.\n\n### Prinsip Rekayasa Perangkat Lunak\n> *\"Software yang hebat bukan sekadar kode yang bebas bug, melainkan arsitektur yang mudah dirawat (maintainable), mudah diskalakan (scalable), dan dapat dipahami dengan jelas oleh tim di masa depan.\"*\n\n### Keahlian & Spesialisasi\n- **Backend Architecture**: Desain modular domain-driven, RESTful API bervolume tinggi, background queue worker, database indexing & query optimization.\n- **Modern Frontend**: SSR/SSG performa tinggi dengan Next.js 16, interactive UI dengan Framer Motion, Tailwind CSS, TypeScript berorientasi tipe ketat.\n- **DevOps & Cloud**: Docker Swarm, Nginx reverse proxy & SSL, Linux automation, CI/CD pipeline, Cloudflare Edge deployment.\n- **Database & Storage**: PostgreSQL (relational design, indexing, jsonb), MySQL/MariaDB, Redis caching layer.\n"
