import fs from "fs"
import path from "path"
import matter from "gray-matter"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const appDir = path.resolve(__dirname, "..")
const rootDir = path.resolve(appDir, "..")

function findContentDir(subfolder) {
  const candidates = [
    path.join(appDir, "content", subfolder),
    path.join(rootDir, "content", subfolder),
    path.join(appDir, "app", "content", subfolder),
  ]
  for (const c of candidates) {
    if (fs.existsSync(c)) return c
  }
  return candidates[0]
}

function calculateReadingTime(text) {
  const words = text.trim().split(/\s+/).length
  const minutes = Math.ceil(words / 180)
  return `${minutes} min read`
}

// 1. Projects
const projectsDir = findContentDir("projects")
let projects = []
if (fs.existsSync(projectsDir)) {
  const files = fs.readdirSync(projectsDir).filter((f) => f.endsWith(".md"))
  projects = files.map((file) => {
    const slug = file.replace(".md", "")
    const raw = fs.readFileSync(path.join(projectsDir, file), "utf-8")
    const { data, content } = matter(raw)
    return {
      slug: data.slug || slug,
      title: data.title || data.judul || slug,
      deskripsi: data.deskripsi || data.description || "",
      tags: Array.isArray(data.tags) ? data.tags : [],
      category: data.category || "Full-Stack",
      featured: Boolean(data.featured),
      date: data.date || "2024",
      role: data.role || "Lead Backend Developer",
      liveUrl: data.liveUrl || "",
      githubUrl: data.githubUrl || "",
      metrics: data.metrics || [],
      content,
    }
  })
  projects.sort((a, b) => (b.featured ? 1 : 0) - (a.featured ? 1 : 0))
}

// 2. Blog Posts
const blogDir = findContentDir("blog")
let posts = []
if (fs.existsSync(blogDir)) {
  const files = fs.readdirSync(blogDir).filter((f) => f.endsWith(".md"))
  posts = files.map((file) => {
    const slug = file.replace(".md", "")
    const raw = fs.readFileSync(path.join(blogDir, file), "utf-8")
    const { data, content } = matter(raw)
    return {
      slug: data.slug || slug,
      title: data.title || slug,
      deskripsi: data.deskripsi || data.description || content.split("\n")[0] || "",
      tags: Array.isArray(data.tags) ? data.tags : [],
      date: data.date || "2024-07-21",
      readingTime: data.readingTime || calculateReadingTime(content),
      content,
    }
  })
  posts.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
}

// 3. Materi
const materiDir = findContentDir("materi")
let materi = []
if (fs.existsSync(materiDir)) {
  const files = fs.readdirSync(materiDir).filter((f) => f.endsWith(".md"))
  materi = files.map((file) => {
    const slug = file.replace(".md", "")
    const raw = fs.readFileSync(path.join(materiDir, file), "utf-8")
    const { data, content } = matter(raw)
    const title = data.judul || data.title || content.split("\n")[0]?.replace(/^#\s+/, "") || slug
    const deskripsi = data.deskripsi || data.description || ""
    const kelas = data.kelas || "Umum"
    return {
      slug: data.slug || slug,
      title,
      kelas,
      deskripsi,
      tags: Array.isArray(data.tags) ? data.tags : [kelas],
      date: data.date || "2024-06-15",
      readingTime: calculateReadingTime(content),
      content,
    }
  })
}

// 4. About
let aboutContent = "Saya Muhammad Habib Abdillah — Full-Stack Developer dengan spesialisasi di PHP, Laravel, Node.js, Next.js, dan arsitektur sistem informasi modular yang scalable."
const aboutCandidates = [
  path.join(appDir, "content", "about.md"),
  path.join(rootDir, "content", "about.md"),
  path.join(appDir, "app", "content", "about.md"),
]
for (const c of aboutCandidates) {
  if (fs.existsSync(c) && !fs.statSync(c).isDirectory()) {
    const raw = fs.readFileSync(c, "utf-8")
    const { content } = matter(raw)
    aboutContent = content
    break
  }
}

const outputFile = path.join(appDir, "lib", "content-data.ts")
const fileContent = `// Auto-generated at build time by scripts/generate-content.mjs
// Do not edit this file directly. Edit the Markdown files in content/ directory instead.
import type { ProjectData, BlogPostData, MateriData } from "./content"

export const projectsData: ProjectData[] = ${JSON.stringify(projects, null, 2)}

export const postsData: BlogPostData[] = ${JSON.stringify(posts, null, 2)}

export const materiData: MateriData[] = ${JSON.stringify(materi, null, 2)}

export const aboutContent: string = ${JSON.stringify(aboutContent)}
`

fs.writeFileSync(outputFile, fileContent, "utf-8")
console.log(`✓ Generated content-data.ts: ${projects.length} projects, ${posts.length} posts, ${materi.length} materi`)
